### ISSUE TITLE
Travis error - incorrect html tag somewhere

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/whitakerlab.github.io#18]
In our [travis log](https://travis-ci.org/WhitakerLab/whitakerlab.github.io/jobs/243670045) we have an `Unexpected end tag : a (line 137)`.

I *think* this is to do with [this section (lines 33 & 35)](https://github.com/WhitakerLab/whitakerlab.github.io/blob/master/_layouts/post.html#L32) in the [_layouts/post.html](https://github.com/WhitakerLab/whitakerlab.github.io/blob/master/_layouts/post.html) file.

I wonder if someone with a little better understanding of html could tell me the right edit to make. I *think* I can just remove the `</a>` tag...but I'd love a sanity check on this :smile:

**Comment by KirstieJane** [comment]
Hi @auremoser, @bmpvieira, @teonbrooks & @acabunoc. Do any of you have time to quickly skim this?? Thank you!!

**Comment by auremoser** [comment]
Hot take, but this feels weird for me:

`<img src="{{ author.avatar }}" class="bio-photo" alt="{{ author.name }} bio photo"></a>` 

To your point, because it closes an `<a href>` that I can't immediately see the source/start of, so either add that href to preceed the `<img>` or remove the `</a>`

**Comment by teonbrooks** [comment]
echo @auremoser, I don't think you need the trailing </a>

**Comment by KirstieJane** [comment]
Mega🌟! Thank you @auremoser & @teonbrooks. I'll create an issue in the parent repo & double check that there isn't supposed to be an `<a href>`. Might as well fix the issue there rather than just here 😀 .

**Comment by KirstieJane** [comment]
Fixed in the [master branch](https://github.com/mmistakes/so-simple-theme/pull/246) now and merged to this fork. Yaaaay!
