### ISSUE TITLE
Broken link needs fixing

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/whitakerlab.github.io#27]
[Travis tells me](https://travis-ci.org/WhitakerLab/whitakerlab.github.io/builds/296167450) that we have a broken link: 

```
- ./_site/resources/Mozilla-Science-Mini-Grant-June2017/index.html

  *  External link https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/Example_JupyterNotebook.ipynb failed: 404 No error

htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!
```

We can fix this by replacing the link in the blog post with a link to that file *as it existed* at the time we posted the blog. @Islast - I think you'd be best placed to do that, would you mind?

**Comment by Islast** [comment]
closed by #31 ✨
