### ISSUE TITLE
End of 2019 update from lab members

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/whitakerlab.github.io#95]
Hi everyone!

Please could you add to this issue:

1. A picture (jpg, png etc) of a powerpoint slide that visually illustrates (some part of) what you've done this year.
  * It doesn't have to be (all) work related - figures from analyses etc make sense but you're welcome to add photographs of where you've been or other really exciting things that happened.
2. A paragraph update. You can think of this as a caption for the figure but it would be great if they were reasonably personal and relavent to the lab. It can include information that wasn't included in the picture!
  * Please write in the first person (I did xxxx, I went to xxxx etc).
  * Aim for around 150 words
  * Links are heavily encouraged!

**Comment by pherterich** [comment]
![2019_review](https://user-images.githubusercontent.com/8457675/71090974-2524b980-219c-11ea-8710-ce6c0cebb32a.png)

I’m proud to have been invited to be part of the [_Turing Way_](https://the-turing-way.netlify.com/introduction/introduction) core team developing a handbook completely in the open and building a community around it. Working on the project has given me the confidence to present at events again and renewed trust in my skills (technical knowledge as well as organizing and running events), highlighted areas of expertise and shown me what I really value in interactions and collaborations. I successfully applied for a [Software Sustainability Institute Fellowship](https://software.ac.uk/blog/2019-04-11-announcing-2019-software-sustainability-institute-fellows), became a carpentries instructor and found a new job that aligns more with my values and beliefs. They both provide me with opportunities to give back to the open community that has supported me in the past and I can’t wait to start mentoring for the Open Life Science programme and get involved in other open projects in 2020.

**Comment by sgibson91** [comment]
![SG_WhitakerLab](https://user-images.githubusercontent.com/44771837/71168457-ab013d00-224e-11ea-824b-203a9b84d720.jpg)

I am proud of how my presenting skills have developed over the last year. While I never considered teaching and public speaking to be my strongest skills, I can take pride in having received very positive feedback. I'm also proud of the network of amazing people I've managed to surround myself with. I'm also really proud to have been invited to join the mybinder.org operating team.

* Applied to be a 2020 SSI Fellow 🤞🤞🤞and openly developed the application on GitHub
* Took initiative to contribute/organise for the community
* People actually ask my opinion on things now, like I know what I'm talking about. And they think it's a good idea for me to express those opinions on a panel at RSE Con.

_[Sorry, I know this a bit piece-meal and rubbish. I'm having real difficulty convincing my brain that it needs to work in full sentences today.]_

**Comment by kwagstyl** [comment]
![year_summary-01](https://user-images.githubusercontent.com/20108230/71167891-7b056a00-224d-11ea-913c-206df88a5195.png)
After 10 years being a student, 2019 was the year I finally finished medicine and started full time in research. I've absolutely loved reinvigorating existing collaborations and starting new ones. 
The MELD project continues to expand, with new sites, researchers and clinical validation projects. It's been great to see the spreading enthusiasm for working openly in the field.
One highlight this year was leading my first open science workshop. It was a real joy sharing the diverse, openly available tools that are part of our workflow and seeing how everyone in the room wanted to try them out immediately.
One thing I've realised this year is that I work best with others. Working so openly in MELD has made it much easier to collaborate. For 2020 I hope to do the same with my work on cortical microstructure - making the tools and data for analysing cortical layers and columns more open and accessible.

**Comment by LouiseABowler** [comment]
My 2019 in a couple of paragraphs:

A common theme for me throughout 2019 has been finishing things - it's the first time I've wrapped up projects at the Turing, and I also tied up some loose ends from my PhD and finally graduated.

The TMF visualisation project has been my most technical project at the Turing so far. I really enjoyed the move into web development and visualisation, and I learnt so much over the course of the project. Looking back at the code now, I can see how far I've come - it's very difficult to say that I've made the "final, final" change!

The Turing Way has been a huge influence on me this year - as an introvert, working openly in a big team was initially a daunting step for me, but I have really come to value how the effort we put into building the community is reflected in peoples' acceptance, friendliness, politeness and helpfulness throughout the entire project. I'm sure the Turing Way is in for another successful year, and I'm looking forward to seeing it happen.

![louises-2019](https://user-images.githubusercontent.com/25640708/71383762-b7322500-25d5-11ea-8b55-492b668be92f.jpg)

Thanks to the Turing's Research Engineering Group for the photo from RSECon.

**Comment by sparkler0323** [comment]
<img width="790" alt="aa" src="https://user-images.githubusercontent.com/18514015/71181307-c890cf80-226b-11ea-8f3a-e947144e66a7.png">

2019 is a special year for me as a visiting student in the UK and I appreciate Kirstie a lot to give me this opportunity. Living in London means that I have to rent a room and cook for myself. I can do really good cooking now and have fun with my landlord's dog (shown in the picture)! 

I have worked with Kirstie and Yini to develop a registered report based on the ABCD project, with all code and pipeline available. Several of my other works also went well. At the same time, I learned a lot from Kirstie in the use of Github as well as the Turing Way. I'm excited in preparation for contributing a new section in power analysis. Really looking forward to more chapters in the Turing Way. 

I have attended several really wonderful conferences in Europe, including [Cambridge Network Day](https://www.cnn.group.cam.ac.uk/cambridge-networks-day), [OHBM](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageID=3882&activateFull=true) and [luminous workshop](http://www.luminous-project.eu/index.php/workshop-studying-measuring-and-altering-consciousness/), and they are all amazing! Moreover, I gave my first English presentation in public at the Turing mental health group.

**Comment by GeorgiaHCA** [comment]
<img width="1070" alt="Screenshot 2019-12-19 at 15 25 39" src="https://user-images.githubusercontent.com/46889966/71185723-e104e800-2273-11ea-8c0e-70105226d627.png">

2019 has been a year of many new horizons! I've loved my first year at the Turing -so many amazing people and projects, and of course Kirstie's amazing mentoring 💖. Python turned out not be as scary as it looked, but just as loopy! And GitHub is friendly after all. 

I've especially enjoyed working with all my autistic collaborators. The insight group has been really enlightening, and I've loved learning about open science, reproducibility, and neuroscience from lab members. I've had the chance to deliver my project at conferences and events, and learned a huge amount - MozzFest, the ODI conference, and the eLife sprint all stand out - thanks so much for test-running my game, Yini, Ang and Patricia.

**Comment by emdupre** [comment]
![Screenshot_2019-12-19 Untitled presentation](https://user-images.githubusercontent.com/15017191/71193095-86f62980-2257-11ea-8589-8005d9c473e9.jpg)


I'm spending the end of 2019 feeling really lucky for being where I am; to be working with so many wonderful, passionate people; and to have the freedom to explore topics I'm really excited about.

For me, it was the year of joining the [Neuro-AI community here in Montreal](https://sites.google.com/view/unique-neuro-ai), speaking at an international conference for the first time in the OHBM [open science symposium](https://figshare.com/articles/Enabling_Open_Publishing_Building_Open_Tools_with_Open_Communities/8292269), and heading back to [Neurohackademy](https://neurohackademy.org/) for the first time since 2016 -- but this time as an instructor ! It was also a year of building stronger communities for open source projects I really care about, like [tedana](https://tedana.readthedocs.io) and [nilearn](http://nilearn.github.io).

**Comment by minnieho1115** [comment]
![nini2019](https://user-images.githubusercontent.com/35134464/71198700-495fc380-228c-11ea-976f-5ef7f3d913aa.png)

This was the first time I stay in a foreign country for such a long time. I am so grateful that you always gave me hands. I never felt alone at Turing, and everyone in our lab is invisible energy for me. Many thanks. With your help, I can face my disadvantage, leave my comfort zone and start moving forward.

It is my pleasure to take part in the ABCD project, and from this project, I learned the ideas of open science from Kirstie. It is happy for me to study python with Georgia. Ang taught me a lot about genetic research and became my programming teacher. 

I hope I can take part in and make contributions to the Turing way in the New Year!!!
（ The second picture was copied from Kirstie's twitter :kissing_heart: ）

**Comment by KirstieJane** [comment]
![WhitakerLab_Kirstie_EndofYear2019](https://user-images.githubusercontent.com/3626306/71424691-12beea00-268c-11ea-9336-6a920b4c6432.png)

As I reflect on 2019 it's heart warming to realise how many of my favourite moments were actually great successes of others. It has been a joy this year to mentor and support so many incredible people. To go around my picture, spiralling inwards from the top left:

* I've loved living in Greenwich this year, the view from my apartment is beautiful and I'm so glad to be able to walk Luna through the park to our favourite coffee shop over the weekends.
* [Georgia](https://github.com/GeorgiaHCA/) has been doing incredible work on the [Autistica/Turing Citizen Science project](https://github.com/alan-turing-institute/AutisticaCitizenScience) and I'm so excited to build the community in 2020.
* I'm still really enjoying working at the [Alan Turing Institute](https://www.turing.ac.uk) and proud to have helped to shape the Tools, Practices and Systems research programme in 2019.
* [csv,conf,v4](https://csvconf.com/2019) was an incredible experience, particularly because I got to hang out with incredible friends (such as [Danielle](https://codeforscience.org/#people) pictured here with Rojo the llama). All conferences should start with a spa afternoon!
* The [Binder workshops](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops) this year were spectacular. Huge thank yous to the wonderful [_Turing Way_](https://the-turing-way.netlify.com) team who made them happen! 
* I'm proud to have spent a lot of time this summer thinking about how to [connect lab members together](https://github.com/WhitakerLab/Onboarding/blob/lab-meetings/Lab-meetings.md) in a strong, resilient, decentralised network. I'm not sure we're totally there yet, but I think we're making good progress.
* I think this Baby Groot card from [Elizabeth](https://elizabeth-dupre.com/) is the greatest thing I've ever seen and it reminds me to focus on the things I have control of and to let go of my jealousy as best I can [#GrootGif](https://twitter.com/search?q=%23GrootGif) style 🙌 
* This year I started going over to write with [Kelly Clancy](http://www.kellybclancy.com/) and I wrote up 10 simple rules to run an open and inclusive community online. I didn't get the paper done 🤦‍♀ but I did [give a talk](https://www.youtube.com/watch?v=2O7O_MU4Le4) on the topic and I love this little infographic!
* I couldn't reflect on the year and _not_ include the spectacular _Turing Way_ [Book Dashes](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops/book-dash) 📚 💨💨 These were a bit of a random idea I had that worked out better than I could ever have imagined. THANK YOU so much to the team for running them, and the amazing community for coming and contributing so much to the book.
* I've put in the figure from Daphne and my paper in eLife on [Data science for the scientific life cycle](https://doi.org/10.7554/eLife.43979) because I love this paper so much. (Not included, but a paper I _also_ love is the one that [James Hetherington](https://www.turing.ac.uk/people/programme-directors/james-hetherington) led on [Design choices for productive, secure, data-intensive research at scale in the cloud](https://arxiv.org/abs/1908.08737).)
* And to finish, that little picture of the dude looking all cool in his shades and visor, is of James, my wonderful boyfriend just before he ran his first 50 mile ultra marathon. I couldn't do the work I do without him. I am a kite and he lets me fly ❤️ 

There are so many things I couldn't fit into this picture. Everyone's contributions in the lab are so deeply valued. I'm so privileged to work with everyone mentioned in this blog post. Thank you so much to you all. Here's to many more exciting times together in 2020.
